// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"
	"github.com/giovanniberi93/einride-backend-onboarding/internal/svc/freightsvc"
)

// Injectors from wire.go:

func Init(contextContext context.Context, config *Config) (*App, func(), error) {
	server := &freightsvc.Server{}
	grpcServer := initGRPCServer(contextContext, server)
	app := &App{
		GRPCServer: grpcServer,
	}
	return app, func() {
	}, nil
}
