// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"context"
)

// Injectors from wire.go:

func Init(contextContext context.Context, config *Config) (*App, func(), error) {
	server := initGRPCServer(contextContext)
	app := &App{
		GRPCServer: server,
	}
	return app, func() {
	}, nil
}
