apiVersion: serving.knative.dev/v1
kind: Service

metadata:
  name: onboarding

spec:
  template:
    spec:
      containers:
        - env:
            - name: GRPC_GO_RETRY
              value: "on"
